# Generated by Django 4.1.2 on 2026-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='allometric',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='run',
            name='n0',
            field=models.FloatField(default=10000000000.0, help_text='Initial tumour burden, in cells.'),
        ),
    ]
