# Generated by Django 4.1.2 on 2026-09-07 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_run_allometric_run_n0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(default='John Doe', max_length=100)),
                ('weight_kg', models.FloatField(default=70.0)),
                ('n0', models.FloatField(default=10000000000.0)),
                ('horizon_days', models.PositiveIntegerField(default=120)),
                ('intervals', models.JSONField(default=list)),
                ('preset_keys', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Complete'), ('error', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
