# Generated by Django 4.1.2 on 2026-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sweep'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Seeded example run. Visible to every visitor in public mode.'),
        ),
        migrations.AddField(
            model_name='sweep',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Seeded example sweep. Visible to every visitor in public mode.'),
        ),
    ]
